### ISSUE TITLE
Other galaxy types: ['mws'], ['bgs'], ['lrg'], ['elg']

### ISSUE THREAD

**Issue by eyu22** [michaelJwilson/DESI-HighSchool#1]
I have a question about what the other types of galaxies (['mws'], ['bgs'], ['lrg'], ['elg']) are. If 'qso' stands for "quasi-stellar-objects" what do the others stand for? Also, more information about the other types would be greatly appreciated. Thanks!

**Comment by michaelJwilson** [comment]
Hello, 
  that's great, thank you.  I'll update the notebooks with a brief intro. to the types (and your other suggestions) and
spin off a new notebook on ELGs (emission line galaxies).  Thanks for the feedback and stay tuned.

**Comment by michaelJwilson** [comment]
I've added a new OII notebook.  It's a bit of a step up so feel free to add comments here when you get stuck.  Good luck!

**Comment by michaelJwilson** [comment]
We'e spun off on #2 for the OII notebook so think we're done with this one!
