### ISSUE TITLE
SnowWhiteDwarf_es not loading

### ISSUE THREAD

**Issue by alxogm** [michaelJwilson/DESI-HighSchool#16]
Hi, not sure why this notebook si not loading... 
Espanol/SnowWhiteDwarf_es.ipynb

The English version annotated with Spanish does... @mmarianav I assume you were able to load it without problems... can you try now?

**Comment by alxogm** [comment]
@mmarianav nevermind, I've found the bug. I'll fix it... thanks

**Comment by michaelJwilson** [comment]
This is done, right?

**Comment by alxogm** [comment]
Yes, sorry I forgot to close the issue... closing now
