### ISSUE TITLE
DESI High Challenge I:  Una celebración de la astronomía hispanoamericana

### ISSUE THREAD

**Issue by michaelJwilson** [michaelJwilson/DESI-HighSchool#19]
To celebrate National Hispanic Month, Independence days throughout the Americas, and the release of DESI High in Spanish, we're writing a new notebook that celebrates Hispanic American astronomy.  The final notebook will likely have roughly three parts: 

1)  Introduction and fun python experiments associated to historic astronomy, e.g. Chichen Itza.  We've provided an example of this to help get you started! 
 
2)  Introduction and fun experiments related to early pioneers of modern Hispanic American astronomy, e.g. Paris Pismis, Guillermo Haro and many others.  This could potentially include the spectrum of _one_ target acquired during DESI SV, particularly if it's already available at DESI High.  Contact us directly if you're working with SV data not currently available.

3)  Introduction and fun experiments related to the work of Hispanic Americans in DESI.  This should not significantly overlap with the DESI main science cases covered in other notebooks, but certainly a new spin could be tried.  In this instance, the shorter the better as a number of entries will likely be included. 

4)  Just submit a welcome that includes an intro. to yourself, your group, where you work and the areas of DESI science that you're interested in!  Check out the [example profiles](https://github.com/michaelJwilson/DESI-HighSchool/blob/master/Espanol/Profiles/) of DESI High developers for the format!  If you submit any of the longer entries above, make sure to include a profile aswell.   
   
If you have an idea to contribute, leave urls to a DESI High fork with your implementation and a [jupyter notebook viewer](https://nbviewer.jupyter.org/) url that points to your finished notebook.  The final notebook will combine the best examples from each.  If you have any questions, leave them in the thread below together with a contact email address.

Submissions are due by _October 15th 2020._

**Comment by michaelJwilson** [comment]
Recreating the corresponding tracks of Venus from Cichen Itza that match to recorded Mayan glyphs with pyephem is my first attempt.  It's sandbox/HispanicCelebration.ipynb

**Comment by alxogm** [comment]
Descripción del reto DESI High Challenge I: Una celebración de la astronomía hispanoamericana.

Para celebrar el Mes Nacional Hispano, los días de celebración de Independencia en las Américas, y el lanzamiento de DESI High en español, estamos escribiendo un nuevo cuaderno (notebook) que celebra la astronomía Hispanoamericana. El cuaderno final tendrá tres partes: 

1.- Introducción y experimentos divertidos en Python relacionados con astronomía ancestral, e.g. Chichen Itza. ¡Hemos puesto un ejemplo para ayudarte a empezar!  
2.- Introducción y experimentos relacionados con los pioneros de la astronomía hispanoamericana moderna, e.g.  Paris Pismis, Guillermo Haro, entre otros. Esto puede hacer uso de algún objeto observado durante la validación de DESI, particularmente  si ya está disponible en DESI high. Contáctanos directamente si pretendes usar datos de SV que no están disponibles actualmente.  
3.- Introducción y experimentos relacionados al trabajo de investigadores hispanoamericanos en DESI. Esto no debe superponerse significativamente con la ciencia principal de DESI que se cubre en otros cuadernos, pero si puede ser desde un nuevo enfoque o extensión. En este caso, mientras más pequeño sea, mejor, ya que es muy posible que incluyamos varios. 

También puedes simplemente enviar una entrada que incluya una descripción tuya, de tu grupo de trabajo, etc, y las áreas de ciencia con DESI en que tienes interés. Usa el mismo formato que nuestro perfil de ejemplo. Si te decides a enviar alguna de las otras tres opciones, asegúrate de incluir tu perfil también. 

Si tienes alguna de contribución, deja el link de tu fork de DESI High que tiene tu implementación y un link a un visor de jupyter notebook, que muestre tu cuaderno terminado. El cuaderno final combinará los mejores ejemplos de cada sección descrita. Si tienes cualquier pregunta, déjala abajo junto con un email de contacto.

**Comment by michaelJwilson** [comment]
Recreating the corresponding tracks of Venus from Cichen Itza that match to recorded Mayan glyphs with pyephem is my first attempt. It's https://nbviewer.jupyter.org/github/michaelJwilson/DESI-HighSchool/blob/master/sandbox/MayaToDESI.ipynb

**Comment by michaelJwilson** [comment]
Closing this to start over in a fresh ticket above; let's get Spanish in second, before any label changes.

**Comment by michaelJwilson** [comment]
-->  #36
