### ISSUE TITLE
OII Broken Link and Unlabeled Graphs

### ISSUE THREAD

**Issue by eyu22** [michaelJwilson/DESI-HighSchool#2]
Hi Dr. Wilson,

Could you double check the link between cells 26 and 27 in OII: [www.en.wikipedia.org/wiki/Diffraction_grating](url) ?
It results in an Error 404. I think you want [en.wikipedia.org/wiki/Diffraction_grating](url).
Can you also add code to label the x and y axes of the graphs in Output 28 and Output 30 (the Gaussian functions)? I'm confused about what they're displaying exactly.

Thanks, and everything else looks great!

**Comment by michaelJwilson** [comment]
Thanks!  This is all fixed up.  There's also a nbody.ipynb that you might not have seen yet - fairly basic, but hopefully fun.   
Think we're done with this one for now.  Feel free to leave more suggestions were you found things harder going. 

Finally, we were selected for https://jupytercon.com, which should be fun.  If we could send this out to your Astronomy group this week or so, you can all hopefully take part (to some extent at least!).
