### ISSUE TITLE
Suggestion: Don't include .ipynb_checkpoints and __pycache__/*.pyc

### ISSUE THREAD

**Issue by RafaelCenzano** [michaelJwilson/DESI-HighSchool#3]
Normally don't save any .pyc files as that is compiled python. Python will generate these when running and sometimes having old versions in the project can give issues with caching.

.ipynb_checkpoints are just personal checkpoints that aren't usually needed.

**Comment by michaelJwilson** [comment]
Hi Rafael, 
  thanks for the catching those accidental additions!  Seems you're well used to GitHub.  Let us know if there's anything else you notice or find interesting.
