### ISSUE TITLE
Google Colab. vs Binder

### ISSUE THREAD

**Issue by michaelJwilson** [michaelJwilson/DESI-HighSchool#51]
Pros, Cons and tests.

**Comment by biprateep** [comment]
https://www.dataschool.io/cloud-services-for-jupyter-notebook/

Check out the above post which does an in depth comparison between the two.
What I see is that both are very similar and we do not need to worry about up times at the scales in which we are operating(~100 users). People seem to be teaching entire classes and workshops using binder pretty easily.

In terms of ease of use the things that you may consider.
- Binder uses plain old Jupyter. Collab has a different interface. So, if you expect that people will be already familiar with jupyter then, Binder might be the more user friendly option.
- Collab works via google drive and hence collaborating is very easy (just like google docs). The notebooks are automatically version controlled and synced to google drive. This might be a useful thing for us.

The blog post above goes in to more things so feel free to check it out @michaelJwilson

**Comment by michaelJwilson** [comment]
We're deep enough into Jupyter and Binder that this ship has sailed.
